name: Deploy

on:
  push:
    branches: ["main"]
      
  pull_request:
    types:
      - "closed"

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code...
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ env.IMAGE_NAME }}:latest

      - name: Push images to Github Registry
        run: |
          docker push ghcr.io/${{ env.IMAGE_NAME }}:latest
